# Generated by Django 3.2.4 on 2021-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
